# Site settings
title: LostTechne
email: support@losttechne.com
url: https://losttechne.com
description: "Develops the world based on technology<br>that is difficult to reproduce in the future."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: "#000000"
  primary-white: "#ffffff"
  links: "#219ab3"

# Footer settings
footer: LostTechne

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
